name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGINECYRILLE }} # Replace with your Docker Hub username
          password: ${{ secrets.xW4zQXF_FY6Z }} # Replace with your Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your_docker_username/your_image_name:latest

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: your_docker_username/your_image_name:latest
          format: 'table'
          exit-code: '1'
