name: CI/CD Pipeline  # Define the name of the workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  schedule:
    - cron: '0 0 * * *'  # Run the Trivy scan every day at midnight
  workflow_dispatch:  # Allow manual trigger of the workflow via the GitHub Actions UI

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Step 1: Checkout the repository code
        uses: actions/checkout@v4.2.0  # Use version 4 for the GitHub checkout action

      - name: Set up Docker Buildx  # Step 2: Set up Docker Buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3.7.1  # Updated to latest version

      - name: Log in to Docker Hub  # Step 3: Log in to Docker Hub using GitHub secrets
        uses: docker/login-action@v3.3.0  # Updated to the correct version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Reference DockerHub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Reference DockerHub password secret

      - name: Build Docker image  # Step 4: Build Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/flask-web-app:${{ github.sha }} .

      - name: Push Docker image to Docker Hub  # Step 5: Push the Docker image to DockerHub
        uses: docker/build-push-action@v6.9.0  # Updated to latest version
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/flask-web-app:latest
            docker.io/${{ secrets.DOCKER_USERNAME }}/flask-web-app:${{ github.sha }}

  scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      - name: Checkout code  # Step 1: Checkout the repository for the scan job
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner  # Step 2: Run Trivy to scan the built image for vulnerabilities
        id: trivy  # Assign an ID for output reference
        uses: aquasecurity/trivy-action@0.20.0  # Use Trivy action v0.20.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/flask-web-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Fail the workflow if vulnerabilities are found  # Step 3: Ensure the job fails if vulnerabilities are found
        if: ${{ steps.trivy.outputs.vulnerability_count > 0 }}
        run: |
          echo "Vulnerabilities found in image, failing the workflow."
          exit 1
