name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGINECYRILLE }} 
          password: ${{ secrets.xW4zQXF_FY6Z }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: reginecyrille/flask-web-app:latest

      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.56.1 
        with:
          image-ref: reginecyrille/flask-web-app:latest
          format: 'table'
          exit-code: '1'
